#!/bin/bash

# Example script for the Othello assignment. Don't forget to make it executable (chmod +x othello)
# Change the last line (java Othello ...) to suit your needs
# Author: Ola Ringdahl

# Change directory to the location of your java program (src folder in this case)
# $(dirname "$0") is the path to where this script is
cd "$(dirname "$0")/out/artifacts/NaiveOthello_jar"

# Call your Java program:
#java othello $1 $2
java -jar othello.jar $1 $2
